### PR TITLE
Make the pid file match the defaults in the init

### LINKED ISSUE #28: Poor default location for stunnel.pid
The default location for the stunnel pidfile is /tmp which gets removed by most distributions /tmp cleanup, causing chef to fail after several days when this file gets removed.  

Chef fails with:

```
STDOUT: Starting SSL tunnels: [Failed: /etc/stunnel/stunnel.conf] You should check that you have specified the pid= in you configuration file
```

### PR DESCRIPTION
**Pull request by onlyhavecans**
This change shouldn't be breaking but will not actually make a meaningful change to the system until the service is restarted. But some testing might be good.
Fixes #28

### CODE REVIEW

**Comment by martinisoft** [comment]
Since #34 greatly enhances the test suite, may want to hold off on a merge and rebase to that?

**Comment by onlyhavecans** [comment]
Agreed. After #34 I will rebase

**Comment by martinisoft** [comment]
Since it seems #34 is dead in the water we may just want to merge this now and I'll work on a separate PR to upgrade the test suite, etc.

**Comment by martinisoft** [comment]
While I am here I will get this whipped up into a release shortly.

**Comment by martinisoft** [comment]
Actually, did you want to hold off on this until we get the suite in better shape on master?

**Comment by onlyhavecans** [comment]
> Actually, did you want to hold off on this until we get the suite in better shape on master?

not unless you feel that's a blocker

**Comment by onlyhavecans** [comment]
It seems there is no interest in merging this.
I will close this but please free to re-open if it is viable for merge

**Pull request closed without merging**
